Update publish script and make it more robust

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
 # Builds the HTML documentation files from the reStructuredText source,
 # then copies the HTML files created by Sphinx, from the 'freeseer-docs' repo
@@ -10,7 +10,7 @@
 # Author(s):
 # Dennis Ideler <ideler.dennis at gmail.com>
 #
-# Copyright 2012  Free and Open Source Software Learning Centre (FOSSLC)
+# Copyright 2012-2013  Free and Open Source Software Learning Centre (FOSSLC)
 # http://fosslc.org
 #
 #  This program is free software: you can redistribute it and/or modify
@@ -35,13 +35,14 @@ set -o errexit
 # Verify all parameters are set.
 #set -o nounset
 
+# Build the HTML output.
 make html
 
-echo "Locating freeseer.github.com repository..."
-REPO=$(find $HOME -type d -name freeseer.github.com)
+echo "Locating freeseer.github.io repository..."
+REPO=$(find $HOME -type d -name freeseer.github.io)
 
 # Exit if not found.
-if [ "$REPO" = "" ]; then echo "freeseer.github.com repo not found!"; exit 1; fi
+if [ "$REPO" = "" ]; then echo "freeseer.github.io repo not found!"; exit 1; fi
 
 # Keep track of freeseer-docs location.
 DOCS="$( cd "$( dirname "$0" )" && pwd )"
@@ -52,7 +53,18 @@ pushd "$REPO/docs" >/dev/null || { echo "You don't have the latest revision!"; e
 echo "Copying docs..."
 cp -rp $DOCS/build/html/* .
 
-echo "Publishing docs..."
+# Check if the local branch has diverged from the remote branch, abort if so.
+if [ `git log --pretty=%H ...refs/heads/master^` != `git ls-remote origin -h refs/heads/master | cut -f1` ]
+then
+  echo "Your master branch and origin/master have diverged"
+  git fetch origin --quiet
+  git log HEAD..origin/master --graph --abbrev-commit --date=relative \
+    --pretty=format:"%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset"
+  echo "***aborted: Please switch to your freeseer.github.io repo and sync it with origin"
+  exit 1
+fi
+
+echo "Staging and committing changes..."
 git add .
 
 # Use custom commit message if provided.
@@ -62,7 +74,12 @@ else
   git commit -m 'Updating docs'
 fi
 
-git push # May require user's GitHub password.
+echo "Deploying to GitHub..."
+if !(`git push origin master --quiet`)  # May require user's GitHub password.
+then
+  echo "***error: Changes not deployed to GitHub, push failed"
+  exit 1
+fi
 
 # Silently switch back to the original directory.
 popd >/dev/null
